<?php require_once  VIEWS.'header.php'; ?>

<!-- -----------------------[ Parallax image ] ----------------------- -->
	<div class='parallax'>
		<p></p>
	</div>
<!-- -----------------------[ Parallax image end] ----------------------- -->
<!-- -----------------------[ Divine container ] ----------------------- -->
<div class='divine-container-reverse'>
	<div class='divine-container-reverse-stage'>
		<div class='divine-content-left-reverse' >
			<div class='storage-content'>
				<h1 class="dwclBlue"><a href='#'>SPECIAL HOLIDAY: October 31, 2019, November 1-2, 2019</a></h1>
				<div class='littleSpace'>
					<p>Posted on November 04, 2019 at 8:40AM</p>
				</div>
				<h3>In accordance with the Memo.20,s. 2019, there will be no classes and work on the following dates:</h3>
				<div class='littleSpace'>
					<p>October 31, 2019 (Thursday) - DWCL Institutional Holiday</p>
					<p>November 1, 2019 (Friday) - All Saint's Day</p>
					<p>November 2, 2019 (Satruday) - All Soul's Day</p>
				</div>
				<h3>Please be guided, Divinians.</h3>
			</div>

			<div class='storage-content'>
				<h1 class="dwclBlue"><a href='#'>SPECIAL HOLIDAY: February 16, 2018</a></h1>
				<div class='littleSpace'>
					<p>Posted on February 12, 2018 at 3:03 PM.</p>
				</div>
				<p>Office of the President</p>
				<p>Memo No. 06, s.2018</p>
				<p>12 February 2018</p>
				<p>To: The DWCL Community</p>
				<p>Subject: February 16, 2018, a Special Holiday</p><hr>
				<p>Please be informed that February 16, 2018(Friday) is declared as a special holiday by virtue of Proclamation No. 269, in observance of the Chinese New Year.</p>
				<p>In view of this, there will be no work and classes in all levels. Classes and work will resume on Saturday, February 17, 2018.</p>
				<p>Please be guided accordingly.</p>
				<div class='littleSpace'>
					<p>Fr. Nielo M. Cantilado, SVD</p>
					<p>President</p>
				</div>
			</div>

			<div class='storage-content'>
				<h1 class="dwclBlue"><a href='#'>MT. MAYON ADVISORY:SUSPENSION OF CLASSES</a></h1>
				<div class='littleSpace'>
					<p>Posted on January 26, 2018 at 7:59 AM.</p>
					
				</div>
				<img src="" class='storage-img storage-img1'>
			</div>

			<div class='storage-content'>
				<h1 class="dwclBlue"><a href='#'>SUSPENSION OF CLASSES</a></h1>
				<div class='littleSpace'>
					<p>Posted on January 15, 2018 at 2:24 PM.</p>
					
				</div>
				<p>15 January 2018</p>
				<p>Memo No. 01, s. 2018</p>
				<div class='littleSpace'>
					<p>To: The Deans and Principals</p>
					<p>Subject: Suspension of Classes</p>
				</div><hr>
				<p>In view of the advisory from Hon. Noel Rosal, Mayor of Legazpi City, classes in all levels are suspended starting at 12 noon today, January 15, 2018.</p>
				<p>Please be guided accordingly.</p>
				<p>May St. Arnold Janssen, Founder of the Society of the Divine Word (SVD), whose Feast Day we celebrate today, guard and protect us all.</p>
				<p>signed:</p>
				<div class='littleSpace'>
					<p>Fr. Nielo M. Cantilado, SVD</p>
					<p>President</p>
				</div>
			</div>

			<div class='storage-content'>
				<h1 class="dwclBlue"><a href='#'>DWC-Legazpi Community – Important Announcements</a></h1>
				<div class='littleSpace'>
					<p>Posted on December 15, 2017 at 10:10 AM.</p>
					
				</div>
				<div class='littleSpace'>
					<p>From the Office of the President</p>
					<p>Memon No. 25, s. 2017</p>
				</div>
				<div class='littleSpace'>
					<p>To: DWCL COMMUNITY</p>
					<p>Subject: IMPORTANT ANNOUNCEMENTS</p>
				</div><hr>
				<p>Please be informed of the following important announcements:</p>
				<ul>
					<li>Institutional Christmas Party – December 16,2017, 7:00 a.m. at St. Joseph Freinademetz Gymnasium</li>
					<li>Christmas Vacation begins – December 20,2017</li>
					<li>Regular classes and work resume – January 3 ,2017</li>
				</ul>
				<p>MAOGMANG PASKO ASIN MAOGMANG BAGONG TAON 2018!</p>
				<p>Please be guided accordingly.</p>
				<p>signed:</p>
				<div class='littleSpace'>
					<p>Fr. Nielo M. Cantilado, SVD</p>
					<p>President</p>
				</div>
			</div>

			<div class='storage-content'>
				<h1 class="dwclBlue"><a href='#'>PDRRMC Advisory No. 4</a></h1>
				<div class='littleSpace'>
					<p>Posted on December 14, 2017 at 10:00 AM.</p>
					
				</div>
				<h3 class="dwclBlue">Office of the President</h3>
				<p>December 14, 2017</p>
				<p>Memo No. 26, s. 2017</p>
				<p>To: DWCL Community</p><hr>
				<p>Subject: PDRRMC Advisory No. 4</p>
				<p>As per PDRRMC Advisory No. 4 on TD Urduja, classes in all levels are suspended at 1:00 p.m., December 14 and 15, 2017.</p>
				<p>Prelim Examinations are re-scheduled as follows:</p>
				<ul>
					<li>December 18, 2017 for MWF classes</li>
					<li>December 19, 2017 for TTH classes</li>
				</ul>
				<p>Please be guided accordingly.</p>
				<div class='littleSpace'>
					<p>(SGD)Fr. Nielo M. Cantilado, SVD</p>
					<p>President</p>
				</div>
			</div>

			<div class='storageNextPrevBtn'>
				<div class='storage-newer storage-btn dwclBlue'><i class='fa fa-angle-left'></i><a href="#">Newer post</a></div>
				<div class='storage-older storage-btn dwclBlue'><a href="#">Older post</a><i class='fa fa-angle-right'></i></div>
			</div>
		</div>
		<?php require_once  VIEWS.'latestPost.html'; ?>
	</div>
</div>

<!-- -----------------------[ Divine container end ] ----------------------- -->
<?php require_once  VIEWS.'footer.php'; ?>