@extends('AboutUsPage.aboutUsOverview')

@section('title', 'History')
@section('body-right')
	<p>The Divine Word College of Legazpi (DWCL) sprang into existence from a small school, Liceo de Albay (LDA), a diocesan school of Caceresfor boys. In 1947 the LDA was entrusted to Fr. Juan Carullo, a retiredarmy chaplain. The members of the Board of Trustees were then Msgr. Justiniano Romano, Fr. Euferto Alberto, Fr. Alfonso Molina, Fr. GuilermoRejante, Fr. William Rehente and Fr. RusticoBurce.  The school building was located at Corners Rizal St. and Maria Clara St. (now Fr. Joseph L. Bates St.),Legazpi City.  The lot was donated by the Calleja family of Legazpi City.</p>
	<p>In 1952, the LDA was ravaged by Typhoon Trix. Financial incapacity became a major problem for its survival. To save the school from possible closure, series of negotiations to take over the management of the school were done between the then Bishop of Legazpi, Bishop Flaviano B. Ariola, D.D. and the SocietasVerbiDivini (SVD) Congregation. Both agreed andofficially turned over the Liceo de Albay by Bishop Flaviano B. Ariola, D.D. to the Provincial Superior of SVD, Fr. Alfonse Lesage, SVDin 1961.The Society of the Divine Word appointed Fr. Joseph L. Bates, SVD, to officially administer the school withMsgr. Honesto A. Moraleda, a diocesan clergy, as Principal. The new school kept its exclusivity for the education of boys with the help of Msgr. Nestor C. Cariño and the then Frt. Florante Camacho, SVD as Regent.</p>
	<p><b>Grade School Department.</b> In 1965, the Grade School Department started its operation, and got its government recognition in 1966. In 1991, the Pre-School in the Grade School Department was also opened.In its aim of improving the quality education for the young, it took its initial steps and submitted itself for the Preliminary Survey Visit on February 26-27, 2007.It had a formal visit on December 2-3, 2008, and a Resurvey Visit on November 28-19, 2011 by the Philippine Accrediting Association of Schools, Colleges and Universities (PAASCU). The department was granted Level II accreditation status valid for 2012-2017. The Grade School has been reaccredited for another five years, valid for 2017-2022.</p>
	<p><b>Junior High School Department.</b> In 1992, the High School department offered a Science Oriented Curriculum. Fifty Six (56) freshmen students were admitted. However, due to financial drawback, the program eventually phased out in May 2001. In 1998, the High School department opened Free Secondary Distance Educational Program (FSDEP) for adult working students.And in that same year, on July 31, 1998, the High School department was granted accreditation for Level 1 by PAASCU. In response to the demand to upgrade the quality standards of education, the High School department underwent another accreditation for level II, and was granted for five-year period in 2004. On November 10-11, 2008 visit the department was granted a clean accreditation until 2013. On December 9-10, 2013visit, the department was again granted another clean accreditation for five years, valid up to 2019; and from now on it is called Junior High School. With the nationwide implementation of the Senior High School program in 2016, this department is now called the <i>Junior High School.</i></p>
	<p><b>Senior High School Department.</b> Participating in the government program in innovation of basic education system, the DWCL started acceptingGrade 11 in Senior High Schoolin 2016,offering Academic and Technical Vocational Tracks. In the Academic Track, the DWCL SHS department offers the following strands: Science, Technology, Engineering and Mathematics (STEM), Accountancy, Business and Management (ABM), and General Academic Strands (GAS). In the Technical and Vocational Track, the following strands were offered: Food and Beverages Services (FBS), Cookery, and Computer System Servicing (CSS). To anticipate the increase number of enrolment in the Senior High School, the construction of a three-storey building located at the North Campus took place.</p>
	<p><b>College Department.</b> Back in 1965, the Divine Word High School was elevated to tertiary level, offering Liberal Arts, Commerce, Education and Secretarial Departments, as Divine Word College of Legazpi (DWCL).In 1971, in consortium with the St. Gregory the Great Seminary in Tabaco, Albay, DWCL offered AB-Philosophy program.</p>
	<p>To be responsive to the manpower needs of the growing number of offices and entrepreneurial agencies in the Bicol Region, short-term programs for Accounting Aides and Salesmanship were opened in June 1974. As part of the expansion program in technology and business, the BS Civil Engineering program was opened two years later.</p>
	<p>In recognition of the exemplary performance of DWCL, the AIDES Program of CHED RO V named DWCL the Center for Development in Commerce and Business Education in 1983.  In 1984, the Accountancy Department, in cooperation with the Philippine Association of Collegiate Schools of Business (PACSB) and the Commission on Audit (COA), piloted the three-year program in Government Accounting and Auditing in DWCL.  In the same year, in coordination with the Regional Science Teaching Center at Aquinas University, the Centership for the Training of Private School Elementary Teachers for the implementation of the New Elementary School Curriculum (NESC) in the Bicol Region was established by the Fund for Assistance to Private Education (FAPE).</p>
	<p>In 1987, the BSE and BEED curricula of the Education Department were reopened as a response to the increasing demand for more teachers in the public schools. With greater demands for computer literate professionals and office staff, the Commerce Department opened in 1993 the BS Computer Science (BSCS), BS in Secretarial Administration (BSSA) programs, and Computer Secretarial Course. The BSSA program was later changed to BS in Office Administration (BSOA).</p>
	<p>Education programs were integrated in the AB-curricular programs to qualify the graduates for the Licensure Examination for Teachers (LET).  The Commerce Department offered specialization in Entrepreneurship.  The Accountancy Department introduced a ladderizedcurriculum.  The CPA Review Center was also inaugurated in 1997.</p>
	<p>During the SY 2001-2002, the departments were elevated to the college-status.  Consequently, the Colleges of Accountancy, Engineering and Commerce opened the non-board programs, BS in Management and Accountancy (BSMA), BS in Information Technology (BSIT), BS in Hospitality Management (BSHM) and BS in Business Administration (BSBA) major in Marketing and Legal Management.  In October 2001, the programs of the Colleges of Accountancy, Commerce, Education and Liberal Arts were awarded Level 1 PAASCU Accreditation.</p>
	<p>In 2003, the College of Engineering opened the BS in Electrical Engineering Program.  For that, it was re-named College of Engineering and Computer Studies. All computer program offerings of the College of Commerce were transferred to COECS. It had an adjunct office called Information Technology Support Center.   In November 21, 2003, the curricular programs of the Colleges of Liberal Arts, Education, Commerce and Accountancy merited Level II PAASCU Accreditation for three years.</p>
	<p>The College of Nursing after being granted the “Permit-to-Operate” in the SY 2004-2005, admitted freshmen applicants to its BS in Nursing (BSN) program and trainees in its six-month Caregiver Training program.  In the same school year, the verticalized business education program was implemented by the College of Commerce.  Towards the end of 2005, the College of Commerce, Accountancy and Graduate School of Business and Management (GSBM) were merged to become the College of Business Education.  A year later, the DWCL Call Center (Incubation and Training Center) was opened in a joint venture with two internationally-known entities:  the Information and Communications Technology (ICT) Training and Business Process Outsourcing (BPO) Experts under the John F. Kennedy Foundation and Five9 of USA. During the same year, DWCL joined the Zonal Research Council for Region IV and V based at UP Los Baños.  It also pioneered the first On-Line Enrollment System in the Bicol Region.</p>
	<p>Toimmortalize the memory of the founder, the DWCL Alumni Association, in cooperation with the Office of the Mayor and City Council, succeeded in renaming Maria Clara St., Legazpi City (fronting the college campus) theFr. Joseph Bates St. School year 2007-2008 saw the birth of the programs BS in Biology, BS Psychology and BS Mathematics at the College of Liberal Arts.In school year 2008-2009, the colleges of Arts and Sciences, Education and Business Programs were granted Level II Accreditation by the PAASCU for five (5) years.</p>
	<p>In Summer 2000, the Center for Development, Research and Extension Service (CDRE) was organized under the aegis of the Office of the President.The formal implementation of the community extension service (CES) and research thrusts took off with the Enterprise Development Project (EDP) as a lending program for livelihood activities of beneficiary-employees. The EDP funded the Tulong Aral for poor but deserving students. With initial funding from the Bilance in Netherlands, the CES Adopt-a-Barangay outreach project was inaugurated in Barangay Ditain 1998.  This program was expanded to Barangay Lamba in 2000.  When the Cordaid (formerly Bilance) funding ended, DWCL sustained the program.  With the establishment of the Research Center in 2000, CDRE was dissolved and the CES, Research and Planning divisions became independent bodies under the Office of the President.</p>
	<p>In 2016, new nomenclature was proposed and implemented in different colleges, such as School of Arts and Science (SAS) (formerly College of Arts and Sciences), School of Education (SED) (formerly College of Education), School of Business, Management and Accountancy (SBMA) (formerly College of Business, Management and Accountancy), School of Engineering and Computer Studies (SOECS) (formerly College of Engineering and Computer Studies), School of Nursing (SoN) (formerly College of Nursing), School of Hospitality and Management (SHoM) (formerly College of Hospitality and Management).</p>
	<p><b>Graduate School of Business and Management.</b> As part of the institutional thrust of developing would-be-leaders in the business community, the Graduate School of Business and Management (GSBM) was opened in 1978, offering Master in Business Administration (MBA).In 1980, DWCL was one of the 13 Charter Member-institutions of the Bicol Conference for High Education (BCHE), the forerunner of the Bicol Foundation for Higher Education (BFHE).</p>
	<p>In 1993, the GSBM enriched its MBA curricular offering with specialization in Business Education, Development Management, Enterprise Development and Financial Management.  Two years later, the Master in Public Administration (MPA) and Master in Business Education (MBE) were opened. The latter was particularly designed for the faculty scholarship grantees from the College of Business Education, supported by the Fund for Assistance for Private Education (FAPE) scholarship program in the Bicol Region.</p>
	<p>Curricular enrichments were marked in 1995.  The GSBM programs were expanded with the opening of Master in Public Management (MPM) program.</p>
	<p><b>The Administrators through the Years.</b>The pioneering job of the school administration was handled by Fr. Joseph L. Bates, SVD who became the director of the institution from 1961 to 1971. Fr. Donald Mulrenan, SVD became president from 1968 to 1970 when Fr. Bates went to the United States. In compliance with the move for the Filipinization of educational institutions in the Philippines, the following took over as Presidents of the Divine Word College of Legazpi in their respective terms:</p>
	<ul>
		<li>Fr. Florante S. Camacho, SVD 1970-1973</li>
		<li>Fr. Valentino D. Darunday, SVD 1973-1979</li>
		<li>Fr. Alfredo A. Reyes, SVD 1979-1985</li>
	</ul>
	<p>& 1989-1990</p>
	<ul>
		<li>Fr. Eleuterio S. Lacaron, SVD 1985-1989</li>
		<li>Fr. Restituto A. Lumanlan, SVD 1990-1993</li>
		<li>Fr. Jose M. Calucag, SVD (+) 1994-1999</li>
		<li>Fr. Ignacio C. Joaquin, SVD February 1999 –  May 1999</li>
		<li>Fr. Michael O. Padua, SVD 1999-2002</li>
		<li>Fr. Francisco Antonio T. Estepa, SVD 2002-2007</li>
		<li>Fr. Crispin A. Cordero, SVD 2008 –2017</li>
		<li>Fr. Nielo M. Cantilado, SVD 2017 – Present</li>
	</ul>
@endsection


